name: Create and/or Update GCP Infra

on:
  workflow_dispatch:

# We don't want parallel deployments.
concurrency: develop

jobs:

  # Job that will dynamically set github actions environment based on the branches.

  deploy:
    permissions:
      contents: read
      id-token: write

    name: Deployment
    environment: stage
    runs-on: ubuntu-latest

    steps:
      - name: Pull code into container ğŸ“‹
        uses: actions/checkout@v2

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/887766566173/locations/global/workloadIdentityPools/github-actions-cicd/providers/github-actions-provider"
          service_account: "sa-github-actions-cicd@acquired-storm-428614-i2.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: "acquired-storm-428614-i2"

      - name: Initialize terraform ğŸ¬
        working-directory: ./infra
        shell: sh
        run: |
          terraform init 

      - name: Validate terraform files ğŸ”
        working-directory: ./infra
        shell: sh
        run: |
          terraform validate

      - name: Check format of terraform files ğŸ”
        working-directory: ./infra
        shell: sh
        run: |
          terraform fmt -check

      - name: Plan terraform changes ğŸ“
        working-directory: ./infra
        shell: sh
        run: |
          terraform plan -var-file=_dev.tfvars -out=plans.tfplan

      - name: Apply terraform changes ğŸŒ³
        working-directory: ./infra
        shell: sh
        run: |
          terraform apply -destroy plans.tfplan 